---
- name: Making build space
  hosts: web
  become: yes

  tasks:
  - name: Ensure git package is present
    apt:
      name: git
      state: present

  - name: Ensure project from repo
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello
      dest: /tmp/boxfuse
      clone: yes
      update: yes

  - name: Ensure maven is present
    apt:
      name: maven
      state: present

  - name: Build project with maven
    shell: cd /tmp/boxfuse && mvn package

- name: Prod for java app
  hosts: db
  become: yes

  tasks:
  - name: Ensure tomcat9 package is present
    apt:
      name: tomcat9
      state: present

  - name: Copy war-file from Building-host
    copy:
      src: root@172.55.0.153:/tmp/boxfuse/target/hello-1.0.war
      dest: /var/lib/tomcat9/webapps/

  - name: Ensure tomcat9 service is started
    service:
      name: tomcat9
      state: started
     
