FROM openjdk:8u151-stretch

# Update pacakges and install open-ssh & maven
RUN apt-get update && \
    apt-get -y install openssh-client && \
    apt install maven
    
# Confugure ssh client
COPY id_rsa /root/.ssh/id_rsa
RUN chmod 600 /root/.ssh/id_rsa

# Install docker 18.03 & Clear cache
RUN apt-get -y install apt-transport-https ca-certificates curl gnupg2 software-properties-common && \
    curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add - && \
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" && \
    apt-get update && \
    pt-get -y install docker-ce=18.03.1~ce-0~debian && \
    apt-get clean
