pipeline {
  agent {
    
    docker {
      image ''
    }
  }

  stages {

      stage('Delete workspace before build starts') {
          steps {
              echo 'Deleting workspace'
              deleteDir()
          }
      }


    stage ('Checkout git') {
      steps {
        git 'https://github.com/svdevops07/boxfuse-sample-java-war-hello.git'
      }
    }

    stage('Build and push Docker Image to registry') {
          steps {
              sh 'docker build -t svdevops07/dz11.jenkins2:0.1 .'
              withDockerRegistry(credentialsId: 'dockerhub-token', url: 'https://index.docker.io/v1/') {
                  sh 'docker push svdevops07/dz11.jenkins2:0.1'
              }
          }
    }

    stage ('Build') {
      steps {
        sh 'mvn package'
      }
    }

    stage ('Make Docker Image') {
      steps {

      }
    }

    stage ('Deploy') {
      steps {
        deploy adapters: [tomcat9(credentialsId: 'tomcat9-user', path: '', url: 'http://172.55.0.158:8080')], contextPath: 'mywebapp2', war: '**/*.war'
      }
    }
  }
}
